POST http://localhost:8080/api/planos
Content-Type: application/json

{
  "nome": "Basico",
  "valor": 99.00,
  "descricao": "Acesso somente a academia e treinos personalizados",
  "administrador": {
    "id": 1
  }
}