POST http://localhost:8080/api/clientes
Content-Type: application/json

{
  "nome": "Alice Costa",
  "login": "alicec",
  "senha": "senhaAlice2025",
  "cpf": "11122233344",
  "rg": "123456789",
  "dataNascimento": "1990-01-01",
  "email": "alice.costa@example.com",
  "telefone": "+5511987654321",
  "endereco": {
    "estado": "SP",
    "cidade": "Sao Paulo",
    "bairro": "Mooca",
    "logradouro": "Rua A",
    "numero": "10",
    "cep": "01001-000"
  },
  "plano": {
    "id": 1
  }
}