POST http://localhost:8080/api/clientes
Content-Type: application/json

{
  "nome": "Carla Souza",
  "login": "carlas",
  "senha": "senhaCarla2025",
  "cpf": "33344455566",
  "rg": "345678901",
  "dataNascimento": "1995-03-22",
  "email": "carla.souza@example.com",
  "telefone": "+5511981234567",
  "endereco": {
    "estado": "MG",
    "cidade": "Belo Horizonte",
    "bairro": "Centro",
    "logradouro": "Rua C",
    "numero": "30",
    "cep": "30110-010"
  },
  "plano": {
    "id": 1
  }
}