POST http://localhost:8080/api/clientes
Content-Type: application/json

{
  "nome": "Bruno Santos",
  "login": "brunos",
  "senha": "senhaBruno2025",
  "cpf": "22233344455",
  "rg": "234567890",
  "dataNascimento": "1985-05-12",
  "email": "bruno.santos@example.com",
  "telefone": "+5511998765432",
  "endereco": {
    "estado": "RJ",
    "cidade": "Rio de Janeiro",
    "bairro": "Copacabana",
    "logradouro": "Rua B",
    "numero": "20",
    "cep": "22010-010"
  },
  "plano": {
    "id": 1
  }
}