POST http://localhost:8080/api/administradores
Content-Type: application/json

{
  "nome": "Matheus Araujo Pereira",
  "login": "matheusaraujopereira",
  "senha": "123456789",
  "cpf": "06318913580",
  "rg": "123456789",
  "dataNascimento": "2001-06-19",
  "email": "matheusaraujopereira@outlook.com.br",
  "telefone": "79999984882"
}