POST http://localhost:8080/api/planos
Content-Type: application/json

{
  "nome": "Premium",
  "valor": 199.00,
  "descricao": "Acesso a atividades extras além dos treinos personalizados",
  "administrador": {
    "id": 1
  }
}