spring.application.name=academia

spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=matheus
spring.datasource.password=1906
spring.jpa.hibernate.ddl-auto=update