POST http://localhost:8080/api/professores
Content-Type: application/json

{
  "nome": "João da Silva",
  "login": "joaosilva",
  "senha": "senhaSegura123",
  "cpf": "98765432101",
  "rg": "7654321",
  "dataNascimento": "1980-05-15",
  "email": "joao.silva@example.com",
  "telefone": "+5511999998888",
  "endereco": {
    "estado": "RJ",
    "cidade": "Rio de Janeiro",
    "bairro": "Copacabana",
    "logradouro": "Avenida Atlântica",
    "numero": "1500",
    "cep": "22021-001"
  }
}